### ISSUE TITLE
crash report

### ISSUE THREAD

**Issue by schriftgestalt** [filipenegrao/glyphsapp-scripts#1]
I got this crash report from a user:
```
Traceback (most recent call last):

 File "~/Library/Application Support/Glyphs 3/Scripts/vanilla/vanillaBase.py", line 506, in action_
   self.callback(sender)

 File "~/Library/Application Support/Glyphs 3/Repositories/Filipe Negrão/italics/slant_glyphs.py", line 153, in selected_glyphs_callback
   self.matrix(a, h, v)

 File "~/Library/Application Support/Glyphs 3/Repositories/Filipe Negrão/italics/slant_glyphs.py", line 144, in matrix
   raise e

 File "~/Library/Application Support/Glyphs 3/Repositories/Filipe Negrão/italics/slant_glyphs.py", line 138, in matrix
   math.radians(angle), (center), # y skew factor

NameError: name 'center' is not defined
```

**Comment by schriftgestalt** [comment]
ping
